// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';

export function ExportAlertCommands():Promise<string>;

export function GetAlertCommands():Promise<commands.AlertCommandsFile>;

export function ImportAlertCommands():Promise<string>;

export function PickAlertMediaFile(arg1:string):Promise<string>;

export function PreviewAlert(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveAlertCommands(arg1:commands.AlertCommandsFile):Promise<void>;
