// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlertCommands() {
  return window['go']['commands']['Commands']['GetAlertCommands']();
}

export function PickAlertMediaFile(arg1) {
  return window['go']['commands']['Commands']['PickAlertMediaFile'](arg1);
}

export function PreviewAlert(arg1, arg2, arg3) {
  return window['go']['commands']['Commands']['PreviewAlert'](arg1, arg2, arg3);
}

export function SaveAlertCommands(arg1) {
  return window['go']['commands']['Commands']['SaveAlertCommands'](arg1);
}
