// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FlushChat() {
  return window['go']['test']['Test']['FlushChat']();
}

export function SendTestMessage(arg1) {
  return window['go']['test']['Test']['SendTestMessage'](arg1);
}
