// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FlushChat():Promise<void>;

export function SendTestMessage(arg1:string):Promise<void>;
