// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {configuration} from '../models';

export function ConfigPath():Promise<string>;

export function GetSettings():Promise<configuration.SettingsForm>;

export function GetTTSVoices():Promise<Array<configuration.TTSVoice>>;

export function PickCommandsFile():Promise<string>;

export function PickMediaDirectory():Promise<string>;

export function SaveSettings(arg1:configuration.SettingsForm):Promise<void>;
