// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigPath() {
  return window['go']['configuration']['Configuration']['ConfigPath']();
}

export function GetSettings() {
  return window['go']['configuration']['Configuration']['GetSettings']();
}

export function GetTTSVoices() {
  return window['go']['configuration']['Configuration']['GetTTSVoices']();
}

export function PickCommandsFile() {
  return window['go']['configuration']['Configuration']['PickCommandsFile']();
}

export function PickMediaDirectory() {
  return window['go']['configuration']['Configuration']['PickMediaDirectory']();
}

export function SaveSettings(arg1) {
  return window['go']['configuration']['Configuration']['SaveSettings'](arg1);
}
