// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';

export function ApplyAndQuit():Promise<void>;

export function Check():Promise<update.Status>;

export function Download():Promise<void>;
