// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAndQuit() {
  return window['go']['update']['Update']['ApplyAndQuit']();
}

export function Check() {
  return window['go']['update']['Update']['Check']();
}

export function Download() {
  return window['go']['update']['Update']['Download']();
}
