// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOBSStatus() {
  return window['go']['home']['Home']['GetOBSStatus']();
}

export function GetRunStatus() {
  return window['go']['home']['Home']['GetRunStatus']();
}

export function InterruptTTS() {
  return window['go']['home']['Home']['InterruptTTS']();
}

export function LookupLatestStream(arg1, arg2) {
  return window['go']['home']['Home']['LookupLatestStream'](arg1, arg2);
}

export function Start() {
  return window['go']['home']['Home']['Start']();
}

export function Stop() {
  return window['go']['home']['Home']['Stop']();
}
