// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {home} from '../models';

export function AppVersion():Promise<string>;

export function GetOBSStatus():Promise<home.OBSStatus>;

export function GetRunStatus():Promise<home.RunStatus>;

export function InterruptTTS():Promise<void>;

export function LookupLatestStream(arg1:string,arg2:string):Promise<home.StreamLookup>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
