// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function GetOBSStatus() {
  return window['go']['main']['App']['GetOBSStatus']();
}

export function GetRunStatus() {
  return window['go']['main']['App']['GetRunStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
