// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function GetOBSStatus() {
  return window['go']['main']['App']['GetOBSStatus']();
}

export function GetRunStatus() {
  return window['go']['main']['App']['GetRunStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTTSVoices() {
  return window['go']['main']['App']['GetTTSVoices']();
}

export function InterruptTTS() {
  return window['go']['main']['App']['InterruptTTS']();
}

export function LookupLatestStream(arg1, arg2) {
  return window['go']['main']['App']['LookupLatestStream'](arg1, arg2);
}

export function PickCommandsFile() {
  return window['go']['main']['App']['PickCommandsFile']();
}

export function PickMediaDirectory() {
  return window['go']['main']['App']['PickMediaDirectory']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendTestMessage(arg1) {
  return window['go']['main']['App']['SendTestMessage'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
