// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfigPath():Promise<string>;

export function GetOBSStatus():Promise<main.OBSStatus>;

export function GetRunStatus():Promise<main.RunStatus>;

export function GetSettings():Promise<main.SettingsForm>;

export function GetTTSVoices():Promise<Array<main.TTSVoice>>;

export function InterruptTTS():Promise<void>;

export function LookupLatestStream(arg1:string,arg2:string):Promise<main.StreamLookup>;

export function PickCommandsFile():Promise<string>;

export function PickMediaDirectory():Promise<string>;

export function SaveSettings(arg1:main.SettingsForm):Promise<void>;

export function SendTestMessage(arg1:string):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
