// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfigPath():Promise<string>;

export function GetOBSStatus():Promise<main.OBSStatus>;

export function GetSettings():Promise<main.SettingsForm>;

export function SaveSettings(arg1:main.SettingsForm):Promise<void>;
